parameters:
    exception_maps:
        AppBundle\Endpoint\Api\Exception\ValidationException :
            { status_code: 422, formatter: AppBundle\Endpoint\Api\Exception\ValidationExceptionFormatter }

services:
    app.infr.http.json_mapper:
        class: JsonMapper
        autowire: true

    app.infr.http.command_mapper:
        class: InfrBundle\Http\ParamConverter\CommandParamConverter
        arguments:
            - '@validator'
            - '@app.infr.http.json_mapper'
            - '@security.token_storage'
        tags:
            - { name: request.param_converter, priority: -2, converter: command_mapper }

    app.infr.http.double_dispatch_resolver:
        class: InfrBundle\Http\ParamConverter\DoubleDispatchParamConverter
        arguments:
            - '@service_container'
        tags:
            - { name: request.param_converter, priority: -2, converter: dd_resolver }

    app.infr.http.exception_listener:
        class: InfrBundle\Http\EventListener\ExceptionResponseListener
        arguments:
            - '%exception_maps%'
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.exception', priority: -64 }

    app.infr.http.request_body_listener:
            class: InfrBundle\Http\EventListener\RequestBodyListener
            tags:
                - { name: kernel.event_listener, event: kernel.request, priority: 64 }

    app.domain.event_dispatcher:
        class: InfrBundle\Domain\Event\Dispatcher
        arguments:
            - '@event_dispatcher'
        tags:
            - { name: doctrine.event_listener, event: postFlush, connection: default }