version: '2'
services:
    gateway:
        build:
            context: ./gateway
        container_name: ts_gateway
        environment:
             - VIRTUAL_HOST=ts.docker
             - VIRTUAL_PORT=80
        depends_on:
             - api
    api:
        build:
            context: ./api
        container_name: ts_api
        environment:
            - SYMFONY__DATABASE__NAME=${DB_NAME}
            - SYMFONY__DATABASE__USER=${DB_USER}
            - SYMFONY__DATABASE__PASS=${DB_PASS}
            - SYMFONY__APP__SECRET=${APP_SECRET}
            - SYMFONY__STORAGE__ACCESS__KEY=${STORAGE_ACCESS_KEY}
            - SYMFONY__STORAGE__SECRET__KEY=${STORAGE_SECRET_KEY}
        volumes:
             - ./api:/app

    database:
        image: postgres:9.4
        container_name: ts_database
        ports:
             - 0.0.0.0:5433:5432
        environment:
             - POSTGRES_USER=${DB_USER}
             - POSTGRES_DB=${DB_NAME}
             - POSTGRES_PASSWORD=${DB_PASS}
             - PGPASSWORD=${DB_PASS}

    storage:
        image: minio/minio
        ports:
            - "9000:9000"
        volumes:
            - storage_data:/export
        environment:
            - MINIO_ACCESS_KEY=${STORAGE_ACCESS_KEY}
            - MINIO_SECRET_KEY=${STORAGE_SECRET_KEY}
        command: server /export


    uploader:
        build:
            context: ./uploader
            dockerfile: provision/Dockerfile
        container_name: ts_uploader
        volumes:
            - ./uploader:/usr/src/app


volumes:
    storage_data: {}