version: '2'
services:
    web:
        build:
            context: ./provision/nginx
        container_name: ts_web
        environment:
             - VIRTUAL_HOST=ts.docker
             - VIRTUAL_PORT=80
        depends_on:
             - app
    app:
        build:
            context: ./provision/php-fpm
        container_name: ts_app
        volumes:
             - ./:/app

    database:
        image: postgres:9.4
        container_name: ts_database
        ports:
             - 0.0.0.0:5433:5432
        environment:
             - POSTGRES_USER=ts_user
             - POSTGRES_DB=ts_db
             - POSTGRES_PASSWORD=ts_pass
             - PGPASSWORD=ts_pass
