# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]


    app.inf.request.request_mapper:
        class: AppBundle\Infr\Request\RequestMapper
        autowire: true
        tags:
            - { name: request.param_converter, priority: -2, converter: request_mapper }