app_login_check:
    path: /api/login

user:
    resource: "@UserBundle/Endpoint/Api/"
    type:     annotation
    prefix:   "/api/users"

video:
    resource: "@VideoBundle/Endpoint/Api/"
    type:     annotation
    prefix:   "/api"

