services:
    app.handler.user.create:
        class: AppBundle\Handler\User\CreateUserHandler
        arguments:
            - '@domain.user.repository'
            - '@event_dispatcher'
            - '@security.password_encoder'
