services:
    app.handler.user.create:
        class: AppBundle\Handler\User\CreateUserHandler
        arguments:
            - '@domain.user.repository'
            - '@event_dispatcher'
            - '@domain.user.password_encoder'

    app.handler.video.create:
            class: AppBundle\Handler\Video\CreateVideoHandler
            autowire: true