services:
    aws.s3.client:
        class: Aws\S3\S3Client
        arguments:
            -
                version: latest
                region: us-east-1
                endpoint: http://storage:9000
                credentials:
                    key: "%storage_access_key%"
                    secret: "%storage_secret_key%"

    app.infr.json_mapper:
        class: JsonMapper
        autowire: true

    app.infr.storage_chuck_uploader:
        class: AppBundle\Infr\Storage\S3ChunkUploader
        autowire: true

    app.infr.upload_session_storage:
        class: AppBundle\Infr\Storage\UploadSessionStorage
        arguments:
            ['@snc_redis.storage']